package main

var blockedDomainList = []string{
	"appspot.com",
	"bit.ly",
	"blogger.com",
	"blogspot.com",
	"feedburner.com",
	"fbcdn.net",
	"fbstatic-a.akamaihd.net",
	"facebook.net",
	"facebook.com",
	"ssl.gstatic.com",
	"plus.google.com",
	"talkgadget.google.com",
	"groups.google.com",
	"drive.google.com",
	"t.co",
	"twimg.com",
	"twitpic.com",
	"twitter.com",
	"wordpress.com",
	"youtu.be",
	"youtube.com",
	"ytimg.com",
}
