package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"text/template"
	"time"
)

var errPageRawTmpl = `<!DOCTYPE html>
<html>
	<head> <title>COW Proxy</title> </head>
	<body>
		<h1>{{.H1}}</h1>
		{{.Msg}}
		{{.Form}}
		<hr />
		Generated by <i>cow-proxy</i> at {{.T}}
	</body>
</html>
`

var blockedFormRawTmpl = `<p></p>
		<form action="http://{{.ListenAddr}}/blocked" method="get">
		<input type="hidden" name="host" value={{.Host}}>
		<b>Refresh to retry</b> or
		<input type="submit" name="add" value="Add {{.Domain}} to blocked sites">
		</form>
`

// Do not end with "\r\n" so we can add more header later
var headRawTmpl = "HTTP/1.1 {{.CodeReason}}\r\n" +
	"Connection: keep-alive\r\n" +
	"Cache-Control: no-cache\r\n" +
	"Pragma: no-cache\r\n" +
	"Content-Type: text/html\r\n" +
	"Content-Length: {{.Length}}\r\n"

var errPageTmpl, headTmpl, blockedFormTmpl *template.Template

func init() {
	var err error
	if headTmpl, err = template.New("errorHead").Parse(headRawTmpl); err != nil {
		fmt.Println("Internal error on generating error head template")
		os.Exit(1)
	}
	if errPageTmpl, err = template.New("errorPage").Parse(errPageRawTmpl); err != nil {
		fmt.Println("Internal error on generating error page template")
		os.Exit(1)
	}
	if blockedFormTmpl, err = template.New("blockedForm").Parse(blockedFormRawTmpl); err != nil {
		fmt.Println("Internal error on generating blocked form template")
		os.Exit(1)
	}
}

func genErrorPage(h1, msg, form string) (string, error) {
	var err error
	data := struct {
		H1   string
		Msg  string
		Form string
		T    string
	}{
		h1,
		msg,
		form,
		time.Now().Format(time.ANSIC),
	}

	buf := new(bytes.Buffer)
	err = errPageTmpl.Execute(buf, data)
	return buf.String(), err
}

func sendPageGeneric(w *bufio.Writer, codeReason, h1, msg, form, addHeader string) {
	page, err := genErrorPage(h1, msg, form)
	if err != nil {
		errl.Println("Error generating error page:", err)
		return
	}

	data := struct {
		CodeReason string
		Length     int
	}{
		codeReason,
		len(page),
	}
	buf := new(bytes.Buffer)
	if err := headTmpl.Execute(buf, data); err != nil {
		errl.Println("Error generating error page header:", err)
		return
	}

	w.WriteString(buf.String())
	w.WriteString(addHeader + "\r\n\r\n")
	w.WriteString(page)
	w.Flush()
}

func sendErrorPage(w *bufio.Writer, codeReason, h1, msg string) {
	sendPageGeneric(w, codeReason, "[Error] "+h1, msg, "", "")
}

func sendRedirectPage(w *bufio.Writer, location string) {
	sendPageGeneric(w, "302 Found", "Domain added to blocked list", "Redirect to "+location,
		"", "Location: "+location)
}

func sendBlockedErrorPage(w *bufio.Writer, codeReason, h1, msg string, r *Request) {
	h, _ := splitHostPort(r.URL.Host)
	if hostIsIP(h) {
		sendErrorPage(w, codeReason, h1, msg)
		return
	}

	data := struct {
		ListenAddr string
		Host       string
		Domain     string
	}{
		config.listenAddr,
		h,
		host2Domain(r.URL.Host),
	}
	buf := new(bytes.Buffer)
	if err := blockedFormTmpl.Execute(buf, data); err != nil {
		errl.Println("Error generating blocked form:", err)
		return
	}
	sendPageGeneric(w, codeReason, "[Error] "+h1, msg, buf.String(), "")
}
